version: '3.1'

services:
#  db:
#    container_name: database
#    image: postgres
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: example
##    env_file:
##      - ".env"

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always